### PR TITLE
Feature/websocket actions

### PR DESCRIPTION
**Pull request by akaplanyan**
added thing_action observer and output to the websocket messages

### CODE REVIEW

**Comment by rwb27** [comment]
Hello, thanks for sending the first pull request not made by me! The websockets are still pretty speculative in here, as you can probably tell, but if you're thinking of using them that is exciting. I'm currently tied up on other projects and am prioritising getting some things packaged and easier to install before I can find time to improve any code, but I should make time to look at this properly when I can.

If you're thinking of using or contributing to labthings, I'd be very interested to hear what you're doing (or thinking of doing) with it. My email shouldn't be hard to find at the University of Glasgow if you'd like to chat directly, or I can usually be found on the OpenFlexure.org forum.

**Comment by rwb27** [comment]
Just to follow up, LabThings does now get published to PyPI, and I've got skeletal docs working. It would be great to add some tests before I merge this - do you have any example code you're happy to share? FastAPI (by which I probably mean Starlette) provides some quite nice features for testing, some of which I've used in `tests/test_websockets.py`. If you don't have time to figure that out, feel free just to paste some example code in here and I'll see if I can convert it.

**Comment by rwb27** [comment]
I'm curious what exactly your planned flow is here: you'd start the action with a POST request, then follow updates using a websocket? From a read of the code, it looks like you'd be observing an Action, rather than one particular Invocation, so you'll get notifications every time it runs.

Following on from some discussion at the Web of Things community group, I think it's worth considering how this could work most nicely. As you currently have it, a websocket can be used to observe an Action - and updates will cover every subsequent Invocation of that action (i.e. if the action can run concurrently or be re-started, all the updates still go to the websocket). I had assumed it would make more sense to observe an Invocation (i.e. one run of an Action): I am curious whether you have reasons for preferring the approach here, or whether that's just what seemed obvious.

One suggestion at the WoT group was that it's cleaner to keep actions on POST requests, because then it's clear that each transaction refers to exactly one invocation. However, that doesn't work well for extended actions that might need to update before they're finished. My thought was that it might make a lot of sense to add an `invokeAction` message type to the websocket: that would start an action, and ensure all of the updates are then returned on that websocket. This has the advantage of ensuring there's no risk of losing an update in between invoking the action with a POST request and observing it on the websocket (though if you're already observing it, that's less of an issue: perhaps I answered my own question above as to why you'd prefer that way).

I don't think this MR need wait for a decision on the above - but as you're already using websockets for actions, I think your opinions here would be valuable.

**Comment by akaplanyan** [comment]
Hi Richard,

Thanks for all of your replies.

To answer some of your questions:

I'm curious what exactly your planned flow is here:
Here is the flow:

  1.
When we load the page, we subscribe to the specific action
  2.
We start an action with post request and get it's action invocation ID
  3.
We listen to all updates for this action invocation ID
  4.
Once action's status is completed, we display the results

To say the truth, we haven't spent much time exploring our options and just went with what you had already implemented for properties and did it in a similar way.

you could presumably come up with some tests quite simply - there's a very basic start in tests/test_websocket.py
I'll look into this in the next couple of days, I think it should be doable

 I've started discussions with "hololinked" about a possible project merge
Thank you for sharing. I've never heard of it but will take a look.

Thanks,
Asia
________________________________

**Comment by akaplanyan** [comment]
Hi Richard,

please take a look at the tests I've added and let me know if we need more

Thanks,
Asia

**Comment by rwb27** [comment]
I'm going to make some tweaks and merge this. Note that we've now adopted the MIT license. I doubt that is controversial, but it's worth being clear here.

**Comment by rwb27** [comment]
With apologies for the force push, I have now merged this in a way that doesn't break the existing tests. The merge commit mentioned above (e0a1664) is gone and replaced by c97847e, which includes a fix for the tests, and a single merge commit back onto `main`.

**Pull request merged**
