### PR TITLE
Switch to MIT license

### PR DESCRIPTION
**Pull request by rwb27**
On discussion with several people, it now seems clear to me that this code is more valuable if it's permissively licensed. I am very keen to encourage commercial adoption and I think an MIT license would facilitate that.

As the current codebase has been written pretty well from scratch, by me, I think my permission is all that's required - though I will mention Joel in the pull request to request his blessing.

### CODE REVIEW

**Comment by rwb27** [comment]
This is prompted in part by discussions with @VigneshVSV about aligning/merging/cross-fertilising `labthings-fastapi` and [`hololinked`](https://github.com/VigneshVSV/hololinked) which are two scientific Python libraries with closely aligned aims and designs.

I don't have a strong preference between MIT and BSD licensing - I have picked MIT because it's simpler.

**Comment by rwb27** [comment]
@jtc42 and I have previously discussed licensing for LabThings, and he was in agreement that a permissive license might make a lot of sense. The present repository doesn't have much code copied wholesale from `python-labthings`, but @jtc42 if you were happy to give this license your blessing that would keep things watertight in the event that I've copied anything over and forgotten about it.

**Comment by VigneshVSV** [comment]
This is really great guys! I have a fork, I will just pull it.

**Comment by jtc42** [comment]
> @jtc42 and I have previously discussed licensing for LabThings, and he was in agreement that a permissive license might make a lot of sense. The present repository doesn't have much code copied wholesale from `python-labthings`, but @jtc42 if you were happy to give this license your blessing that would keep things watertight in the event that I've copied anything over and forgotten about it.

More than happy

**Comment by VigneshVSV** [comment]
I would also appreciate if you guys freely license the old version. There were few good gems there.

**Pull request merged**
